import Foundation

enum BundledNormalLevels {
    static let all: [Int: MazeData] = [
        1: MazeData(
            rows: 15,
            cols: 15,
            grid: [
                "###############",
                "#S#....E#.....#",
                "#O#O#####.##..#",
                "#.#.....O.#...#",
                "#O#########.###",
                "#.....#...#...#",
                "#.###.#.#.###.#",
                "#.#O..#.#...#.#",
                "#.#.###.###.#.#",
                "#...#O..#.#.#.#",
                "#.###O.##.#.#.#",
                "#.........#...#",
                "#.#######.#####",
                "#.............#",
                "###############"
            ],
            start: GridPoint(row: 1, col: 1),
            exit: GridPoint(row: 1, col: 7),
            orbs: [GridPoint(row: 10, col: 5), GridPoint(row: 4, col: 1), GridPoint(row: 9, col: 5), GridPoint(row: 2, col: 3), GridPoint(row: 7, col: 3), GridPoint(row: 2, col: 1), GridPoint(row: 3, col: 8)],
            t2: 11.264000000000001,
            t3: 8.8,
            shortestPath: 64
        ),
        2: MazeData(
            rows: 15,
            cols: 15,
            grid: [
                "###############",
                "#.........#..O#",
                "#.###.#...#.###",
                "#.#O#...#..O#E#",
                "#.#.###.#####.#",
                "#.O...#O....#.#",
                "#####.#####.#.#",
                "#..S#.......#.#",
                "#.###.#.###.#.#",
                "#.#...#...#.#.#",
                "#.#.#.###.###.#",
                "#.#..O..#...#.#",
                "#.#####.###.#.#",
                "#......O.O#...#",
                "###############"
            ],
            start: GridPoint(row: 7, col: 3),
            exit: GridPoint(row: 3, col: 13),
            orbs: [GridPoint(row: 3, col: 3), GridPoint(row: 3, col: 11), GridPoint(row: 13, col: 7), GridPoint(row: 1, col: 13), GridPoint(row: 11, col: 5), GridPoint(row: 5, col: 2), GridPoint(row: 5, col: 7), GridPoint(row: 13, col: 9)],
            t2: 8.096,
            t3: 6.324999999999999,
            shortestPath: 46
        ),
        3: MazeData(
            rows: 17,
            cols: 17,
            grid: [
                "#################",
                "#.....#O....#...#",
                "#.#####.###.#.#.#",
                "#.#.......#.#O#.#",
                "#.#.#######.#O#.#",
                "#.#.#.......#.#S#",
                "#.#.###.#.###O###",
                "#...#.#E..#..O..#",
                "#.#.#.#####.###.#",
                "#.#.......#...#.#",
                "#.#####.#.#####.#",
                "#.......#.......#",
                "#.#.#.#########.#",
                "#...#O.O....#..O#",
                "#####.#.#####.###",
                "#.....#........O#",
                "#################"
            ],
            start: GridPoint(row: 5, col: 15),
            exit: GridPoint(row: 7, col: 7),
            orbs: [GridPoint(row: 6, col: 13), GridPoint(row: 15, col: 15), GridPoint(row: 3, col: 13), GridPoint(row: 4, col: 13), GridPoint(row: 7, col: 13), GridPoint(row: 13, col: 15), GridPoint(row: 13, col: 5), GridPoint(row: 13, col: 7), GridPoint(row: 1, col: 7)],
            t2: 10.208,
            t3: 7.975,
            shortestPath: 58
        ),
        4: MazeData(
            rows: 17,
            cols: 17,
            grid: [
                "#################",
                "#.......#.....#E#",
                "###.###.#.###.#.#",
                "#..O#.....O...#.#",
                "#.#.###.#.#.###.#",
                "#.#.#.....#.#...#",
                "#O#.#.#######...#",
                "#.#.#.......O...#",
                "#.#############O#",
                "#...#O..#...O...#",
                "#.#.#.#.#.#######",
                "#.#O..#...#S....#",
                "#.#############.#",
                "#.#....O......#.#",
                "#.###.###.#.#O#.#",
                "#.....#.....#...#",
                "#################"
            ],
            start: GridPoint(row: 11, col: 11),
            exit: GridPoint(row: 1, col: 15),
            orbs: [GridPoint(row: 9, col: 5), GridPoint(row: 8, col: 15), GridPoint(row: 13, col: 7), GridPoint(row: 9, col: 12), GridPoint(row: 3, col: 3), GridPoint(row: 7, col: 12), GridPoint(row: 11, col: 3), GridPoint(row: 14, col: 13), GridPoint(row: 6, col: 1), GridPoint(row: 3, col: 10)],
            t2: 10.912,
            t3: 8.525,
            shortestPath: 62
        ),
        5: MazeData(
            rows: 19,
            cols: 19,
            grid: [
                "###################",
                "#...#O...O..#.....#",
                "#.#.#.#####.###.#.#",
                "#...#.....#.#...#.#",
                "#.#####.###.O.#####",
                "#O..O.#O#...#.....#",
                "#.###...#.#####.#.#",
                "#.....#.#.#...#...#",
                "###.#.#.###...#.#.#",
                "#...#.#.#.....#.#.#",
                "#####.#.#.###.###O#",
                "#.....#.#.#...#...#",
                "#.###.#.#.###.#.#.#",
                "#...#.#.#.O.#...#.#",
                "#.#.###.#.#.#####.#",
                "#.#E....#O#O#S..#.#",
                "#.#########.#..O#.#",
                "#...........#.#...#",
                "###################"
            ],
            start: GridPoint(row: 15, col: 13),
            exit: GridPoint(row: 15, col: 3),
            orbs: [GridPoint(row: 1, col: 9), GridPoint(row: 15, col: 9), GridPoint(row: 15, col: 11), GridPoint(row: 16, col: 15), GridPoint(row: 1, col: 5), GridPoint(row: 5, col: 1), GridPoint(row: 4, col: 12), GridPoint(row: 13, col: 10), GridPoint(row: 5, col: 7), GridPoint(row: 10, col: 17), GridPoint(row: 5, col: 4)],
            t2: 9.504000000000001,
            t3: 7.425000000000001,
            shortestPath: 54
        ),
        6: MazeData(
            rows: 17,
            cols: 17,
            grid: [
                "#################",
                "#.....#....O..#.#",
                "###.#.#.###v..#.#",
                "#S#.#...#.#...#.#",
                "#.#.#####.#.###.#",
                "#...#.....#.....#",
                "#####O###.#####.#",
                "#..O..#...#.....#",
                "#..####.#.###...#",
                "#....O#.#.....#.#",
                "###.#.#.#####O#.#",
                "#E#...#.....#O#.#",
                "#.#...#####.#.#.#",
                "#.#...#...#.#.#O#",
                "#.###O###O#.###.#",
                "#....<....#.....#",
                "#################"
            ],
            start: GridPoint(row: 3, col: 1),
            exit: GridPoint(row: 11, col: 1),
            orbs: [GridPoint(row: 7, col: 3), GridPoint(row: 9, col: 5), GridPoint(row: 11, col: 13), GridPoint(row: 1, col: 11), GridPoint(row: 10, col: 13), GridPoint(row: 14, col: 9), GridPoint(row: 14, col: 5), GridPoint(row: 13, col: 15), GridPoint(row: 6, col: 5)],
            t2: 12.32,
            t3: 9.625,
            shortestPath: 70
        ),
        7: MazeData(
            rows: 17,
            cols: 17,
            grid: [
                "#################",
                "#.....E...#.....#",
                "###.#####..O###.#",
                "#...#..<#..O#...#",
                "#.#.#.#.#####.###",
                "#.#O#O#^...O#O#O#",
                "#.###.###.#.#.#.#",
                "#.......#.#.O...#",
                "#.#######.#.###.#",
                "#...#...#.#.#...#",
                "#####.#.#.#.#.#.#",
                "#.....#.#.#.#.#.#",
                "#.#####.#O#.###.#",
                "#S#...#.#.#.#>..#",
                "###.#.#.#.#.#.#.#",
                "#...#.....#O..#.#",
                "#################"
            ],
            start: GridPoint(row: 13, col: 1),
            exit: GridPoint(row: 1, col: 6),
            orbs: [GridPoint(row: 3, col: 11), GridPoint(row: 12, col: 9), GridPoint(row: 2, col: 11), GridPoint(row: 5, col: 11), GridPoint(row: 7, col: 12), GridPoint(row: 5, col: 5), GridPoint(row: 5, col: 15), GridPoint(row: 5, col: 3), GridPoint(row: 5, col: 13), GridPoint(row: 15, col: 11)],
            t2: 9.328000000000001,
            t3: 7.2875,
            shortestPath: 53
        ),
        8: MazeData(
            rows: 19,
            cols: 19,
            grid: [
                "###################",
                "#v...S#E..#.......#",
                "#.#####.#.#.#.#####",
                "#..O..#.#...#.....#",
                "#.###.#O#######.###",
                "#O#.O.#.#...#.....#",
                "#.#.#O#.#.#.#.###.#",
                "#.#O#.#.....#...#.#",
                "###.#######.#.#.#.#",
                "#.O.#..O..#...#...#",
                "#.###.#.#########.#",
                "#.....#.......#>..#",
                "#.###.###.^####.###",
                "#...#....>....#...#",
                "###.#.#.#.#.#.###.#",
                "#.#.#O#.#...#vOO..#",
                "#.#.#.#.#####.###.#",
                "#.....#>....#.....#",
                "###################"
            ],
            start: GridPoint(row: 1, col: 5),
            exit: GridPoint(row: 1, col: 7),
            orbs: [GridPoint(row: 6, col: 5), GridPoint(row: 5, col: 1), GridPoint(row: 7, col: 3), GridPoint(row: 4, col: 7), GridPoint(row: 9, col: 2), GridPoint(row: 15, col: 15), GridPoint(row: 9, col: 7), GridPoint(row: 15, col: 5), GridPoint(row: 15, col: 14), GridPoint(row: 3, col: 3), GridPoint(row: 5, col: 4)],
            t2: 13.024000000000001,
            t3: 10.175,
            shortestPath: 74
        ),
        9: MazeData(
            rows: 19,
            cols: 19,
            grid: [
                "###################",
                "#.O.......#v.....v#",
                "#.#########...###.#",
                "#^......#........<#",
                "#.###..##O#.#.#####",
                "#...#....>.O#....O#",
                "###.#.##...######.#",
                "#.OO#.#v....#O.v#.#",
                "#.###...#.#.#.#.#E#",
                "#.#.#.#...#...#.#.#",
                "#.#.#.###.#####...#",
                "#.#...#.#...O.#...#",
                "#.###.#.#.#.#####.#",
                "#S..#...#.#..O..#.#",
                "###.###.#.#.#.#.#.#",
                "#.#.#..^#.#...#.#.#",
                "#.#.#.###.#O#.###.#",
                "#O.......O#.#.....#",
                "###################"
            ],
            start: GridPoint(row: 13, col: 1),
            exit: GridPoint(row: 8, col: 17),
            orbs: [GridPoint(row: 1, col: 2), GridPoint(row: 5, col: 17), GridPoint(row: 13, col: 13), GridPoint(row: 11, col: 12), GridPoint(row: 16, col: 11), GridPoint(row: 7, col: 2), GridPoint(row: 17, col: 9), GridPoint(row: 5, col: 11), GridPoint(row: 7, col: 3), GridPoint(row: 4, col: 9), GridPoint(row: 17, col: 1), GridPoint(row: 7, col: 13)],
            t2: 6.864000000000001,
            t3: 5.3625,
            shortestPath: 39
        ),
        10: MazeData(
            rows: 21,
            cols: 21,
            grid: [
                "#####################",
                "#.....#v............#",
                "#.##.##O#.###.##..#.#",
                "#.......#.......S.#.#",
                "#.#.###############.#",
                "#...#..v.........<#.#",
                "###O#.#.###.#.###.#.#",
                "#.Ov#.#.<.#.#...#..^#",
                "#.#...#...#####.###.#",
                "#.#..O..#.....#...#.#",
                "#.#########.#.###.###",
                "#...#....E#.#..O#^..#",
                "###.#.###.#.###.###.#",
                "#.#.#.#.#.#>OO#>..#.#",
                "#.#.#O#.#.###.#.###.#",
                "#.#.#.....#.OO#O.O#.#",
                "#.#.#.#...#O###.#.#.#",
                "#...#.#...#.#....<..#",
                "#.###.###.#...####>.#",
                "#.....#..^..#.#.....#",
                "#####################"
            ],
            start: GridPoint(row: 3, col: 16),
            exit: GridPoint(row: 11, col: 9),
            orbs: [GridPoint(row: 14, col: 5), GridPoint(row: 13, col: 13), GridPoint(row: 11, col: 15), GridPoint(row: 13, col: 12), GridPoint(row: 9, col: 5), GridPoint(row: 15, col: 15), GridPoint(row: 16, col: 11), GridPoint(row: 2, col: 7), GridPoint(row: 15, col: 13), GridPoint(row: 15, col: 12), GridPoint(row: 6, col: 3), GridPoint(row: 15, col: 17), GridPoint(row: 7, col: 2)],
            t2: 9.68,
            t3: 7.5625,
            shortestPath: 55
        ),
        11: MazeData(
            rows: 17,
            cols: 17,
            grid: [
                "#################",
                "#....O#.#.......#",
                "#...#.#.#.###O#.#",
                "#.#.#.#...#..O#.#",
                "#.#.#.#####.###.#",
                "#.#.#.#.O...#E#.#",
                "###.#.#O#####.#.#",
                "#...#...#.....#.#",
                "#.#######.#####O#",
                "#.#....O#.#.....#",
                "#.#O###.#.#.O##.#",
                "#...#.O.#.......#",
                "#.###.#.#####.###",
                "#.#.#.#.#..O#.#S#",
                "#...#.###.#.###.#",
                "#...#.....#.....#",
                "#################"
            ],
            start: GridPoint(row: 13, col: 15),
            exit: GridPoint(row: 5, col: 13),
            orbs: [GridPoint(row: 3, col: 13), GridPoint(row: 13, col: 11), GridPoint(row: 1, col: 5), GridPoint(row: 2, col: 13), GridPoint(row: 5, col: 8), GridPoint(row: 11, col: 6), GridPoint(row: 10, col: 3), GridPoint(row: 6, col: 7), GridPoint(row: 8, col: 15), GridPoint(row: 10, col: 12), GridPoint(row: 9, col: 7)],
            t2: 16.544,
            t3: 12.925,
            shortestPath: 94
        ),
        12: MazeData(
            rows: 19,
            cols: 19,
            grid: [
                "###################",
                "#.......#...#.....#",
                "#.#####.#O###.#.#.#",
                "#.#...#.#.#EO...#.#",
                "#O#.O.#...#######.#",
                "#.#.#.#.#...#...#.#",
                "#.#.#.#.###.#.#.#.#",
                "#.#.#.#...#.#.....#",
                "#.#.#O#.#.#.#.###.#",
                "#.......#.#..O....#",
                "#.#######.#####.###",
                "#.#....S#....O#.#.#",
                "#.#.#######.###O#.#",
                "#.#.......#.#...#.#",
                "#.#.#####.#.#O###.#",
                "#.#.#..O..#...#...#",
                "#.###.#O#.#.#.###O#",
                "#.....#...#.......#",
                "###################"
            ],
            start: GridPoint(row: 11, col: 7),
            exit: GridPoint(row: 3, col: 11),
            orbs: [GridPoint(row: 4, col: 4), GridPoint(row: 9, col: 13), GridPoint(row: 11, col: 13), GridPoint(row: 3, col: 12), GridPoint(row: 4, col: 1), GridPoint(row: 15, col: 7), GridPoint(row: 8, col: 5), GridPoint(row: 16, col: 7), GridPoint(row: 16, col: 17), GridPoint(row: 12, col: 15), GridPoint(row: 2, col: 9), GridPoint(row: 14, col: 13)],
            t2: 13.024000000000001,
            t3: 10.175,
            shortestPath: 74
        ),
        13: MazeData(
            rows: 19,
            cols: 19,
            grid: [
                "###################",
                "#..........O......#",
                "#.#####.#########.#",
                "#E#O.O..#.....#...#",
                "###.#####.###.#.###",
                "#...#.....#S..#..O#",
                "#.###O#.#########.#",
                "#...#.#.........#.#",
                "###.###...#.#.....#",
                "#...#...#.#...#.#.#",
                "#.#O#.###.#O#.#.#.#",
                "#.#.#.....#.#.#...#",
                "#.#.##..#.###.#####",
                "#.#O#...#...#O....#",
                "#...#.#.###.O.##.##",
                "#.#O#.O.#...#.....#",
                "#.#####.#.#####.#.#",
                "#.......#........O#",
                "###################"
            ],
            start: GridPoint(row: 5, col: 11),
            exit: GridPoint(row: 3, col: 1),
            orbs: [GridPoint(row: 10, col: 11), GridPoint(row: 13, col: 3), GridPoint(row: 13, col: 13), GridPoint(row: 10, col: 3), GridPoint(row: 14, col: 12), GridPoint(row: 1, col: 11), GridPoint(row: 15, col: 6), GridPoint(row: 5, col: 17), GridPoint(row: 3, col: 5), GridPoint(row: 17, col: 17), GridPoint(row: 6, col: 5), GridPoint(row: 15, col: 3), GridPoint(row: 3, col: 3)],
            t2: 9.504000000000001,
            t3: 7.425000000000001,
            shortestPath: 54
        ),
        14: MazeData(
            rows: 21,
            cols: 21,
            grid: [
                "#####################",
                "#.....#.O.#SO.......#",
                "#.#.#...#.#########.#",
                "#.#.....#.......#...#",
                "#.#############.#.#.#",
                "#...#.........#O..#.#",
                "###.#.####.##.#######",
                "#...#...O...........#",
                "#.#######O#.##.####.#",
                "#.#.O...#.....O.#...#",
                "#.#.#.#.#O#.#.#.#.###",
                "#...#.#OO.#...#.#...#",
                "#####.###.###.####..#",
                "#.....#.#.....#.....#",
                "#.#####.#.#O###O###.#",
                "#...#.....#...#.....#",
                "#.#.###.#.###.#.#.###",
                "#.......#.#...#.#...#",
                "#..####.###.###.###.#",
                "#.....#...O...#.OE#.#",
                "#####################"
            ],
            start: GridPoint(row: 1, col: 11),
            exit: GridPoint(row: 19, col: 17),
            orbs: [GridPoint(row: 11, col: 7), GridPoint(row: 10, col: 9), GridPoint(row: 1, col: 12), GridPoint(row: 7, col: 8), GridPoint(row: 9, col: 4), GridPoint(row: 9, col: 14), GridPoint(row: 11, col: 8), GridPoint(row: 14, col: 15), GridPoint(row: 5, col: 15), GridPoint(row: 1, col: 8), GridPoint(row: 14, col: 11), GridPoint(row: 8, col: 9), GridPoint(row: 19, col: 10), GridPoint(row: 19, col: 16)],
            t2: 16.896,
            t3: 13.200000000000001,
            shortestPath: 96
        ),
        15: MazeData(
            rows: 23,
            cols: 23,
            grid: [
                "#######################",
                "#.#.........#...#.#.O.#",
                "#.#O#####.#.#.#.#.#.#.#",
                "#.#.#.....#.#.#.....#.#",
                "#.#....######.#..####O#",
                "#...#.........#.....#S#",
                "#..##############.###.#",
                "#.....#O.....O..#.....#",
                "#####.#...#####.#######",
                "#O......#.#....O......#",
                "###....##.#.######.#..#",
                "#.......#.............#",
                "#.##.##.#.#####.#.##.##",
                "#.#...#...O...#.#.#...#",
                "#.#.#.#.#.#.###.###...#",
                "#.#.#...#...#...#...#.#",
                "#.#.#######.#.#.#.###.#",
                "#......O..#...#...#...#",
                "#.##O##.#...#####.#.###",
                "#.#.......#.....O.#..E#",
                "#.#.#.#..O##.######.#O#",
                "#...#..O...........O..#",
                "#######################"
            ],
            start: GridPoint(row: 5, col: 21),
            exit: GridPoint(row: 19, col: 21),
            orbs: [GridPoint(row: 13, col: 10), GridPoint(row: 2, col: 3), GridPoint(row: 21, col: 7), GridPoint(row: 7, col: 7), GridPoint(row: 9, col: 1), GridPoint(row: 4, col: 21), GridPoint(row: 18, col: 4), GridPoint(row: 19, col: 16), GridPoint(row: 7, col: 13), GridPoint(row: 20, col: 9), GridPoint(row: 1, col: 20), GridPoint(row: 20, col: 21), GridPoint(row: 17, col: 7), GridPoint(row: 21, col: 19), GridPoint(row: 9, col: 15)],
            t2: 12.32,
            t3: 9.625,
            shortestPath: 70
        ),
        16: MazeData(
            rows: 19,
            cols: 19,
            grid: [
                "###################",
                "#.......#E....#...#",
                "#######.#####.#...#",
                "#..O.O#.#....A...O#",
                "#.###...#.#.#####.#",
                "#.#...#O..........#",
                "#.###########...#.#",
                "#.#O........#.#.#O#",
                "#.#...#######.#.#.#",
                "#.#aO........O#.#.#",
                "#.#O.########.#.#.#",
                "#.........#.......#",
                "#.#.#.###...#.##..#",
                "#.#O#...#...#.#...#",
                "#.#...#...###.#.###",
                "#...#.#.....#.#.O.#",
                "#.###########.###.#",
                "#S............#.OO#",
                "###################"
            ],
            start: GridPoint(row: 17, col: 1),
            exit: GridPoint(row: 1, col: 9),
            orbs: [GridPoint(row: 7, col: 3), GridPoint(row: 13, col: 3), GridPoint(row: 7, col: 17), GridPoint(row: 3, col: 5), GridPoint(row: 9, col: 13), GridPoint(row: 17, col: 17), GridPoint(row: 17, col: 16), GridPoint(row: 15, col: 16), GridPoint(row: 10, col: 3), GridPoint(row: 3, col: 17), GridPoint(row: 3, col: 3), GridPoint(row: 5, col: 7), GridPoint(row: 9, col: 4)],
            t2: 6.45,
            t3: 4.95,
            shortestPath: 36
        ),
        17: MazeData(
            rows: 19,
            cols: 19,
            grid: [
                "###################",
                "#..O.....S#....O.O#",
                "#.#########.#.###.#",
                "#.#.........#.O.#.#",
                "#.#.#####O#.###.#.#",
                "#.#...#...#...#..a#",
                "#...#.#A..#.....#.#",
                "#.#.#.#.#.....#...#",
                "#.###.#.#.#.#.#O#.#",
                "#.....#...#.#.#...#",
                "#.###.#####.#..O#.#",
                "#.O.#...#...#.#.#.#",
                "#O...#O.#.###.#.#.#",
                "#....O........#...#",
                "#.#.#.#########.###",
                "#.#...#...........#",
                "#.#.#.#.###.#####.#",
                "#....O...O#.....OE#",
                "###################"
            ],
            start: GridPoint(row: 1, col: 9),
            exit: GridPoint(row: 17, col: 17),
            orbs: [GridPoint(row: 17, col: 16), GridPoint(row: 11, col: 2), GridPoint(row: 3, col: 14), GridPoint(row: 17, col: 5), GridPoint(row: 12, col: 1), GridPoint(row: 1, col: 15), GridPoint(row: 1, col: 17), GridPoint(row: 17, col: 9), GridPoint(row: 10, col: 15), GridPoint(row: 12, col: 6), GridPoint(row: 8, col: 15), GridPoint(row: 13, col: 5), GridPoint(row: 1, col: 3), GridPoint(row: 4, col: 9)],
            t2: 7.744,
            t3: 6.05,
            shortestPath: 44
        ),
        18: MazeData(
            rows: 21,
            cols: 21,
            grid: [
                "#####################",
                "#......O.O......S...#",
                "#.###.###O#######.#.#",
                "#...#...#O#........B#",
                "#.#.###.#.#.#######.#",
                "#...........O.....#O#",
                "#.#.####.####.###.#.#",
                "#O..#.....#...O.#...#",
                "###.#.#O#...##....#.#",
                "#.....#..A..#...#.#.#",
                "#O###########..##.#.#",
                "#.#.............#...#",
                "#.###.#########.#.###",
                "#..b..#...#....a#...#",
                "###.###.###.#.#.##..#",
                "#O#...O.....#.#.#...#",
                "#.#.#########.###O#.#",
                "#.#...#E....#..O#.#.#",
                "#.###.#####.###.#.#.#",
                "#....O........#.....#",
                "#####################"
            ],
            start: GridPoint(row: 1, col: 16),
            exit: GridPoint(row: 17, col: 7),
            orbs: [GridPoint(row: 19, col: 5), GridPoint(row: 2, col: 9), GridPoint(row: 1, col: 7), GridPoint(row: 15, col: 1), GridPoint(row: 5, col: 19), GridPoint(row: 15, col: 6), GridPoint(row: 5, col: 12), GridPoint(row: 8, col: 7), GridPoint(row: 16, col: 17), GridPoint(row: 17, col: 15), GridPoint(row: 1, col: 9), GridPoint(row: 3, col: 9), GridPoint(row: 7, col: 1), GridPoint(row: 7, col: 14), GridPoint(row: 10, col: 1)],
            t2: 8.624,
            t3: 6.7375,
            shortestPath: 49
        ),
        19: MazeData(
            rows: 23,
            cols: 23,
            grid: [
                "#######################",
                "#....O........O.#..O..#",
                "#S######O####...###.#.#",
                "#.#......O..........b.#",
                "#.#.#.#...####.####...#",
                "#...#...O...#...#.....#",
                "#######.#...#.#.#.##.##",
                "#.......#.#.#.#.#.#...#",
                "#.#####.###.#.#.#.#...#",
                "#.#.....O...#.#...#.#.#",
                "#.##.....B###.#.#####.#",
                "#.....#.#...#.#.......#",
                "#.###.#####.#.###..##.#",
                "#....a....#.#.......#.#",
                "#.#######.#.#.#####.#.#",
                "#......O...O#.....#..O#",
                "#O#####.#####.#O###.###",
                "#.....#.#...O.#...#...#",
                "###.#.....#######.#.#.#",
                "#...#...#...#E.O#..A..#",
                "#...#.#####.#.#.#.##..#",
                "#O.O#.........#.......#",
                "#######################"
            ],
            start: GridPoint(row: 2, col: 1),
            exit: GridPoint(row: 19, col: 13),
            orbs: [GridPoint(row: 1, col: 14), GridPoint(row: 21, col: 3), GridPoint(row: 15, col: 11), GridPoint(row: 5, col: 8), GridPoint(row: 15, col: 21), GridPoint(row: 1, col: 19), GridPoint(row: 3, col: 9), GridPoint(row: 16, col: 1), GridPoint(row: 21, col: 1), GridPoint(row: 1, col: 5), GridPoint(row: 2, col: 8), GridPoint(row: 17, col: 12), GridPoint(row: 16, col: 15), GridPoint(row: 9, col: 8), GridPoint(row: 15, col: 7), GridPoint(row: 19, col: 15)],
            t2: 7.920000000000001,
            t3: 6.1875,
            shortestPath: 45
        ),
        20: MazeData(
            rows: 23,
            cols: 23,
            grid: [
                "#######################",
                "#.O....O........#.....#",
                "#...###.#######.#.#...#",
                "#.#.#.........#.#E#...#",
                "###.#.b####.#.#.###.#.#",
                "#...#...#..O#.#.O.#.#.#",
                "#.#####.#.#.#.###.#.#.#",
                "#.#..O#.#...#.#.#.#.#.#",
                "#O#.#.#.#.###.#.#.#.#.#",
                "#.#.#.........#..C..#O#",
                "#.#.####O.#.#######.#.#",
                "#.#...#O....#..O#.....#",
                "#..a#.#.#O#.#.#.#.#####",
                "#B..#OA...#...#...#.O.#",
                "#.#.#...#.###.###.#...#",
                "#.#...#.....#.O....c.O#",
                "#.#####.###.#.#.#.#O#.#",
                "#...#...#.......#.....#",
                "###.#.#######.###.#####",
                "#...#.......#.....#S..#",
                "#..###.##############.#",
                "#.O...................#",
                "#######################"
            ],
            start: GridPoint(row: 19, col: 19),
            exit: GridPoint(row: 3, col: 17),
            orbs: [GridPoint(row: 5, col: 11), GridPoint(row: 11, col: 15), GridPoint(row: 16, col: 19), GridPoint(row: 21, col: 2), GridPoint(row: 11, col: 7), GridPoint(row: 15, col: 14), GridPoint(row: 8, col: 1), GridPoint(row: 15, col: 21), GridPoint(row: 9, col: 21), GridPoint(row: 1, col: 2), GridPoint(row: 10, col: 8), GridPoint(row: 7, col: 5), GridPoint(row: 13, col: 20), GridPoint(row: 12, col: 9), GridPoint(row: 5, col: 16), GridPoint(row: 1, col: 7), GridPoint(row: 13, col: 5)],
            t2: 9.889,
            t3: 7.843,
            shortestPath: 62
        ),
        21: MazeData(
            rows: 19,
            cols: 19,
            grid: [
                "###################",
                "#.............#...#",
                "#####.#...###.#O###",
                "#E...O#...#.#.#...#",
                "#######.###.#.#.#.#",
                "#..O.O.......D....#",
                "###.#.####.O..#.###",
                "#.....#.....#.....#",
                "#.....#.#####.###.#",
                "#O..#...#...#...#O#",
                "#...#..##...###.#.#",
                "#.O.#...#.#.....#.#",
                "###.###.#.#######.#",
                "#O.O#...#O......#.#",
                "#....O#######.#S#.#",
                "#.#.#.......#.O.#.#",
                "#.#....#.O#.#.###.#",
                "#.........#......O#",
                "###################"
            ],
            start: GridPoint(row: 14, col: 15),
            exit: GridPoint(row: 3, col: 1),
            orbs: [GridPoint(row: 13, col: 3), GridPoint(row: 9, col: 1), GridPoint(row: 16, col: 9), GridPoint(row: 15, col: 14), GridPoint(row: 6, col: 11), GridPoint(row: 3, col: 5), GridPoint(row: 13, col: 1), GridPoint(row: 5, col: 3), GridPoint(row: 13, col: 9), GridPoint(row: 17, col: 17), GridPoint(row: 14, col: 5), GridPoint(row: 2, col: 15), GridPoint(row: 11, col: 2), GridPoint(row: 9, col: 17), GridPoint(row: 5, col: 5)],
            t2: 6.9395,
            t3: 5.4395,
            shortestPath: 43
        ),
        22: MazeData(
            rows: 21,
            cols: 21,
            grid: [
                "#####################",
                "#.........#........D#",
                "#.##O##.#.#.###.###.#",
                "#.#.O...#.....#.#.EO#",
                "###.###.#.....#.#.###",
                "#...............#...#",
                "#.###.#.#..##.#.##O##",
                "#.#...#.#...#.......#",
                "#.#.###.###.###.###.#",
                "#.....#...#.O..O..O.#",
                "#..OO####.#.#####.#.#",
                "#.#.....#.#.#.#.....#",
                "###.###.#.#.#.#.#O###",
                "#...#.O...#.#...#.#.#",
                "#.###.#########.#.#.#",
                "#...#.#OO.....#.....#",
                "#.#.#.#.#####.#..##.#",
                "#.#...#.....#.#...#.#",
                "#.###.#####...###O#.#",
                "#O.S#.....O.#.....#.#",
                "#####################"
            ],
            start: GridPoint(row: 19, col: 3),
            exit: GridPoint(row: 3, col: 18),
            orbs: [GridPoint(row: 12, col: 17), GridPoint(row: 15, col: 7), GridPoint(row: 3, col: 19), GridPoint(row: 10, col: 3), GridPoint(row: 18, col: 17), GridPoint(row: 15, col: 8), GridPoint(row: 6, col: 18), GridPoint(row: 13, col: 6), GridPoint(row: 9, col: 12), GridPoint(row: 9, col: 18), GridPoint(row: 19, col: 1), GridPoint(row: 3, col: 4), GridPoint(row: 10, col: 4), GridPoint(row: 19, col: 10), GridPoint(row: 2, col: 4), GridPoint(row: 9, col: 15)],
            t2: 6.6865,
            t3: 5.1865,
            shortestPath: 41
        ),
        23: MazeData(
            rows: 21,
            cols: 21,
            grid: [
                "#####################",
                "#.O.O.....O........E#",
                "#####O##.#####.O#.#O#",
                "#.OO.O#...#...OO..#.#",
                "#.#####O#.#.####.##.#",
                "#...#.....#.........#",
                "#.#.#..##.###D#######",
                "#.#.#...#.......#...#",
                "#.#.###.###.###.#.#.#",
                "#.#.......#.#.......#",
                "#.#########D#.....###",
                "#O#..O#.....#...#.#S#",
                "#....##.##O######.#.#",
                "#.......#.....#...#.#",
                "###.#...#.###.#.###.#",
                "#O..#...#...#...#...#",
                "#..##..###..#####.###",
                "#...#.......#......O#",
                "###.###############.#",
                "#...................#",
                "#####################"
            ],
            start: GridPoint(row: 11, col: 19),
            exit: GridPoint(row: 1, col: 19),
            orbs: [GridPoint(row: 11, col: 1), GridPoint(row: 1, col: 2), GridPoint(row: 11, col: 5), GridPoint(row: 2, col: 5), GridPoint(row: 3, col: 2), GridPoint(row: 2, col: 15), GridPoint(row: 15, col: 1), GridPoint(row: 3, col: 5), GridPoint(row: 12, col: 10), GridPoint(row: 3, col: 3), GridPoint(row: 17, col: 19), GridPoint(row: 3, col: 14), GridPoint(row: 4, col: 7), GridPoint(row: 2, col: 19), GridPoint(row: 1, col: 10), GridPoint(row: 1, col: 4), GridPoint(row: 3, col: 15)],
            t2: 10.208,
            t3: 8.096,
            shortestPath: 64
        ),
        24: MazeData(
            rows: 23,
            cols: 23,
            grid: [
                "#######################",
                "#.....#....O.......O..#",
                "#.###.#.#######.#######",
                "#.S.#...#.....#......O#",
                "###O#.###.#..##.#.#.#.#",
                "#...#.O.#.#.....#...#.#",
                "#..##.#.#.###.#####.#.#",
                "#.....#.O...#.#...#.#.#",
                "#.#.#########.#.#.###.#",
                "#...#...#.....#O#...#.#",
                "#...#.###O##.D#.###.#.#",
                "#.#...#...#.O.#..O#...#",
                "#O###.#.#####.###.###.#",
                "#.#...#.....#a...O#.#.#",
                "#.###O#.#O#.#...###...#",
                "#.....#.#...#.#..O#O..#",
                "###A..#.#...#.###.#####",
                "#...#.......#.#.......#",
                "#.#########.#.#.#.###.#",
                "#...O.......#.#.#...#O#",
                "#.###########.#.#####.#",
                "#.............#.D..E..#",
                "#######################"
            ],
            start: GridPoint(row: 3, col: 2),
            exit: GridPoint(row: 21, col: 19),
            orbs: [GridPoint(row: 15, col: 17), GridPoint(row: 7, col: 8), GridPoint(row: 9, col: 15), GridPoint(row: 3, col: 21), GridPoint(row: 10, col: 9), GridPoint(row: 11, col: 17), GridPoint(row: 14, col: 9), GridPoint(row: 13, col: 17), GridPoint(row: 1, col: 19), GridPoint(row: 19, col: 4), GridPoint(row: 19, col: 21), GridPoint(row: 12, col: 1), GridPoint(row: 1, col: 11), GridPoint(row: 14, col: 5), GridPoint(row: 15, col: 19), GridPoint(row: 4, col: 3), GridPoint(row: 11, col: 12), GridPoint(row: 5, col: 6)],
            t2: 8.4535,
            t3: 6.7044999999999995,
            shortestPath: 53
        ),
        25: MazeData(
            rows: 25,
            cols: 25,
            grid: [
                "#########################",
                "#.......#S........#.....#",
                "#.###.#.#########.#.###.#",
                "#.#...#.#O........#..O..#",
                "#.#.D.#.#.#.##.####.#.###",
                "#.#.#b..#...........#...#",
                "#.#.#...#.#...###.#####.#",
                "#...#.D.#.#.............#",
                "###.###.#.#######.#####.#",
                "#...#...#...#.....#.#...#",
                "#a.##.#######.#..A#.#.###",
                "#.D.#E#.......#.....#.#.#",
                "###.#####.###.O.O.#.#.#.#",
                "#.........#...#O..#.#.#.#",
                "#.#########.#O#.###.#O#.#",
                "#....O....#.#..O#...#...#",
                "#.#..######.#####.B.###.#",
                "#.#.........#...#...O.#.#",
                "#.####..#####.#.#####.#.#",
                "#.......#...O.#.#...#.O.#",
                "#.###...#O#####.#.#.##.##",
                "#.....#.#.O.#.O.#.O.#...#",
                "#######.#.#....##.#.#.#.#",
                "#....O....#..OO...#.....#",
                "#########################"
            ],
            start: GridPoint(row: 1, col: 9),
            exit: GridPoint(row: 11, col: 5),
            orbs: [GridPoint(row: 3, col: 21), GridPoint(row: 3, col: 9), GridPoint(row: 23, col: 14), GridPoint(row: 17, col: 20), GridPoint(row: 21, col: 10), GridPoint(row: 23, col: 13), GridPoint(row: 23, col: 5), GridPoint(row: 15, col: 15), GridPoint(row: 19, col: 22), GridPoint(row: 12, col: 14), GridPoint(row: 13, col: 15), GridPoint(row: 14, col: 21), GridPoint(row: 15, col: 5), GridPoint(row: 20, col: 9), GridPoint(row: 14, col: 13), GridPoint(row: 12, col: 16), GridPoint(row: 19, col: 12), GridPoint(row: 21, col: 14), GridPoint(row: 21, col: 18)],
            t2: 10.208,
            t3: 8.096,
            shortestPath: 64
        ),
        26: MazeData(
            rows: 21,
            cols: 21,
            grid: [
                "#####################",
                "#O.......O.O#.O...O.#",
                "#.#####.#.#...#.###.#",
                "#.....#.#.#.#.......#",
                "#.###.###.#O###.#.###",
                "#.#E..#.OO#...#O#...#",
                "#.###...#####.#.##..#",
                "#...#...#....D#.....#",
                "###.#####.##.###.##.#",
                "#.O.#.............#.#",
                "#O###.#.#.###...#.#.#",
                "#.#...#.........#...#",
                "#.#.#####.###########",
                "#.#.....#........K..#",
                "#.###...#.#####.###.#",
                "#...O.....#...#O#S#.#",
                "#.O.#######.#.###.#.#",
                "#.........#.#.....#.#",
                "#####..##.#.#######.#",
                "#.........#...O.O.O.#",
                "#####################"
            ],
            start: GridPoint(row: 15, col: 17),
            exit: GridPoint(row: 5, col: 3),
            orbs: [GridPoint(row: 9, col: 2), GridPoint(row: 5, col: 8), GridPoint(row: 1, col: 9), GridPoint(row: 19, col: 18), GridPoint(row: 15, col: 4), GridPoint(row: 10, col: 1), GridPoint(row: 19, col: 16), GridPoint(row: 1, col: 11), GridPoint(row: 15, col: 15), GridPoint(row: 5, col: 9), GridPoint(row: 19, col: 14), GridPoint(row: 1, col: 1), GridPoint(row: 1, col: 18), GridPoint(row: 16, col: 2), GridPoint(row: 4, col: 11), GridPoint(row: 5, col: 15), GridPoint(row: 1, col: 14)],
            t2: 11.165,
            t3: 8.854999999999999,
            shortestPath: 70
        ),
        27: MazeData(
            rows: 21,
            cols: 21,
            grid: [
                "#####################",
                "#vO...#....O#.......#",
                "#.#O#.##..#.###.###.#",
                "#.#.#.#...#...#..K#S#",
                "#.#v..#..####.###.###",
                "#.#.#v......#...#...#",
                "#.#.#.#.#.#####...#.#",
                "#.#...#....O#...#...#",
                "#.###...###.#.#####.#",
                "#...#.#.#...#..O....#",
                "#.#O#.#.#....######.#",
                "#..<#...#...O.#....<#",
                "#.#########D#O#.#####",
                "#O#.......#.#..^..#.#",
                "#..D#####O#.#####.#.#",
                "#..^....#.#.......#.#",
                "#OE##.###.#.#.###.#.#",
                "#...#.#.....#..O..#.#",
                "#.###.#O<####.#.###.#",
                "#....O....O..O#O..O.#",
                "#####################"
            ],
            start: GridPoint(row: 3, col: 19),
            exit: GridPoint(row: 16, col: 2),
            orbs: [GridPoint(row: 19, col: 18), GridPoint(row: 17, col: 15), GridPoint(row: 19, col: 10), GridPoint(row: 19, col: 13), GridPoint(row: 11, col: 12), GridPoint(row: 10, col: 3), GridPoint(row: 19, col: 5), GridPoint(row: 14, col: 9), GridPoint(row: 12, col: 13), GridPoint(row: 13, col: 1), GridPoint(row: 9, col: 15), GridPoint(row: 19, col: 15), GridPoint(row: 18, col: 7), GridPoint(row: 7, col: 11), GridPoint(row: 2, col: 3), GridPoint(row: 1, col: 2), GridPoint(row: 16, col: 1), GridPoint(row: 1, col: 11)],
            t2: 8.613,
            t3: 6.8309999999999995,
            shortestPath: 54
        ),
        28: MazeData(
            rows: 23,
            cols: 23,
            grid: [
                "#######################",
                "#O....O..ED.#.....#...#",
                "#.#########.#...###.###",
                "#.#.#...#.O.#.#.....#.#",
                "#.#.#.#.#.###.#######.#",
                "#.....#^..#...#...O...#",
                "#####.#####.###.#.#####",
                "#.....#..O#.....#.....#",
                "#...###.#.#.#.#.#.###O#",
                "#O#.#..O#OK.#.#.#.....#",
                "#.###.#######.#.##..#.#",
                "#.#v.<#...#...#.....#.#",
                "#D#.###.#.#.#O###^^.#.#",
                "#...#...#^..#...#...#.#",
                "#.#####.#.###O#.#.###S#",
                "#...#...#.#...#.#...#.#",
                "###.#.###.#.###.#.###.#",
                "#....^#.#O..#..O#.#.>.#",
                "#.###.#.###O#.###...O##",
                "#....^#^O...#.#..<#...#",
                "#.###.#.###O#.#######.#",
                "#.O.#.....#......O....#",
                "#######################"
            ],
            start: GridPoint(row: 14, col: 21),
            exit: GridPoint(row: 1, col: 9),
            orbs: [GridPoint(row: 8, col: 21), GridPoint(row: 21, col: 17), GridPoint(row: 20, col: 11), GridPoint(row: 5, col: 18), GridPoint(row: 14, col: 13), GridPoint(row: 17, col: 15), GridPoint(row: 1, col: 6), GridPoint(row: 17, col: 9), GridPoint(row: 18, col: 11), GridPoint(row: 9, col: 1), GridPoint(row: 3, col: 10), GridPoint(row: 19, col: 8), GridPoint(row: 7, col: 9), GridPoint(row: 12, col: 13), GridPoint(row: 18, col: 20), GridPoint(row: 21, col: 2), GridPoint(row: 1, col: 1), GridPoint(row: 9, col: 7), GridPoint(row: 9, col: 9)],
            t2: 11.0055,
            t3: 8.728499999999999,
            shortestPath: 69
        ),
        29: MazeData(
            rows: 25,
            cols: 25,
            grid: [
                "#########################",
                "#...O.#.O...#.#.#.......#",
                "###.#.#.#...#O#...#.#####",
                "#...O.#...#...#...#.#...#",
                "#.###.#...#.###.#.#.#.#.#",
                "#.#...#.#.#.....#O#>A.#.#",
                "#.#.###.#..<#####.##.##.#",
                "#.#..v#.#.#.#O..#^....v.#",
                "#.###..<#.#.#...###.#.^##",
                "#...#.#.#.#O..#.#.#.#..v#",
                "#...#.###.#.#.#.#.#.###O#",
                "#.OS#...OO#.<a..#.....#.#",
                "#.#####...##.##.#####.#.#",
                "#.#...........#.#..E#O#.#",
                "#K#.#########.#O#.#.###.#",
                "#.#..O#.........#>......#",
                "#.###.#.#########.#####.#",
                "#...#....O#.....#.D.#...#",
                "#...#.###.##..#.#...###.#",
                "#.#...#>..#v..#D#.....#.#",
                "#.#####.###.###.#####.#.#",
                "#.....O.#...#.#.#..O#.#.#",
                "#.#.#.####Kv#.#.#...#.#.#",
                "#..>OO.....^#..O.^#.D...#",
                "#########################"
            ],
            start: GridPoint(row: 11, col: 3),
            exit: GridPoint(row: 13, col: 19),
            orbs: [GridPoint(row: 13, col: 21), GridPoint(row: 21, col: 19), GridPoint(row: 11, col: 8), GridPoint(row: 7, col: 13), GridPoint(row: 15, col: 5), GridPoint(row: 23, col: 4), GridPoint(row: 5, col: 17), GridPoint(row: 21, col: 6), GridPoint(row: 2, col: 13), GridPoint(row: 23, col: 5), GridPoint(row: 9, col: 11), GridPoint(row: 11, col: 2), GridPoint(row: 1, col: 4), GridPoint(row: 17, col: 9), GridPoint(row: 10, col: 23), GridPoint(row: 14, col: 15), GridPoint(row: 1, col: 8), GridPoint(row: 11, col: 9), GridPoint(row: 23, col: 15), GridPoint(row: 3, col: 4)],
            t2: 10.208,
            t3: 8.096,
            shortestPath: 64
        ),
        30: MazeData(
            rows: 27,
            cols: 27,
            grid: [
                "###########################",
                "#.......#.......#....v#>O.#",
                "#.v#.##.###.#.#.###.#D#.#D#",
                "#^>...#>....#.#.O...#.O.#D#",
                "###.#.#######.#O#.#.###.#.#",
                "#.O...#.......#...#.....#E#",
                "#.###.##.##.###O###..##.###",
                "#.v.#.......#O#...#.>.#...#",
                "#...###..####.#.#.###.##.v#",
                "#.........#..a..#.........#",
                "#.###.#.#.#.#.#.#####.B..##",
                "#...#.#.v.#.#K#.....#.#b..#",
                "#.#......##.#.#.#####.#.#.#",
                "#...#.#..<..#.#.......#.#.#",
                "##>.#...#.#.#.#######.###.#",
                "#...#O#.>^....#...........#",
                "#.###.#..####.##...####.#.#",
                "#.....#.....#.#.....O...#.#",
                "#.###O#O###.#.#.######.##.#",
                "#...#...#.#O#O#.....#...#.#",
                "#.#.#####O#.#.#####.#.###.#",
                "#.#.#...O..<#^.....^.O...^#",
                "###.#.#.#..##.###.#.#..####",
                "#S..#.#..O..#^....OA#.<...#",
                "#.###.#######.#####.###...#",
                "#..K...O.......O..#....O<.#",
                "###########################"
            ],
            start: GridPoint(row: 23, col: 1),
            exit: GridPoint(row: 5, col: 25),
            orbs: [GridPoint(row: 21, col: 8), GridPoint(row: 18, col: 5), GridPoint(row: 3, col: 22), GridPoint(row: 20, col: 9), GridPoint(row: 25, col: 23), GridPoint(row: 15, col: 5), GridPoint(row: 19, col: 13), GridPoint(row: 21, col: 21), GridPoint(row: 25, col: 15), GridPoint(row: 23, col: 18), GridPoint(row: 7, col: 13), GridPoint(row: 3, col: 16), GridPoint(row: 17, col: 20), GridPoint(row: 5, col: 2), GridPoint(row: 19, col: 11), GridPoint(row: 4, col: 15), GridPoint(row: 23, col: 9), GridPoint(row: 18, col: 7), GridPoint(row: 25, col: 7), GridPoint(row: 6, col: 15), GridPoint(row: 1, col: 24)],
            t2: 9.251,
            t3: 7.337,
            shortestPath: 58
        )
    ]
}